# Jekyll Resume Theme

# Site settings
title: Ng Hay Man's Portfolio
email: michelle.hmng@gmail.com
description: Ng Hay Man's Portfolio
baseurl: ""
url: ""
name: NG Hay Man
job: professional writer specialized in transcreation, researcher, gender equality advocate
location: Hong Kong, London
languages: Cantonese, Chinese and English

cv: /assets/Github_CV_MichelleNg.pdf
email_address: michelle.hmng@gmail.com

# Build settings
markdown: kramdown
