# Jekyll Resume Theme

# Site settings
title: Ng Hay-man's Portfolio
email: michelle.hmng@gmail.com
description: Michelle Ng's Portfolio
baseurl: ""
url: ""
name: Michelle Hay-man NG
job: professional writer specialized in transcreation, researcher, gender equality advocate
location: Hong Kong, London
languages: Cantonese, Chinese and English

cv: /assets/Github_CV_MichelleNg.pdf
email_address: michelle.hmng@gmail.com

# Build settings
markdown: kramdown
